apiVersion: v1
kind: Pod
metadata:
  name: multipod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-net-attachment
spec:
  containers:
  - name: multipod-1
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
