apiVersion: v1
kind: Pod
metadata:
  name: multi-vhost-example
  annotations:
    k8s.v1.cni.cncf.io/networks: userspace-ovs, userspace-ovs
spec:
  containers:
  - name: multi-vhost-example
    image: ubuntu-dpdk
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - mountPath: /vhu/
      name: socket
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        memory: 1Gi
      limits:
        hugepages-1Gi: 1Gi
    command: ["sleep", "infinity"]
  volumes:
  - name: socket
    hostPath:
      path: /var/lib/cni/vhostuser/
  - name: hugepage
    emptyDir:
      medium: HugePages
  securityContext:
    runAsUser: 0
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: kube-master-<#>
