apiVersion: v1
kind: Pod
metadata:
  name: with-node-anti-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "node.alpha.kubernetes-incubator.io/nfd-cpuid-AVX"
            operator: DoesNotExist
  containers:
  - name: with-node-anti-affinity
    image: gcr.io/google_containers/pause:2.0
